### ISSUE TITLE
output_FiberStats.txt shoud be named output_FiberStats.csv

### ISSUE THREAD

**Issue by soichih** [kitchell/app-classifiedfibertractstats#1]
The file format like following is known as CSV (RFC4180).

```
Tracts,FiberCount,MeanLength,STDLength,TotalLength,Volume
Left Thalamic Radiation,1013,96.5711321237777,22.0470307172694,97826.5568413868,35384
Right Thalamic Radiation,1202,91.8132208852608,23.1924935691003,110359.491504084,36969
Left Corticospinal,1008,112.962297641981,20.9832029739035,113865.996023117,22805
Right Corticospinal,874,114.622128712817,18.9926941804248,100179.740495002,2315
```

With .csv file extension, a lot of spreadsheet apps / MIME parser can understand the content of the file and open it in proper applications associated with .csv files.  I think it should be updated to output data in .csv instead of .txt. I also think it's a bit redundant with .json. I think either one should be removed. If there is no possibility that value might be nested in the future, I think writing it as .csv is probably the optimal. But json would allow more complex data structure in the future.

Also, the file name could be just "output.csv"?

**Comment by kitchell** [comment]
If you can make it so the information is readable in the browser as a .csv Ill change it. Or create a way to display the information in browser as a table, using the json (or csv) as we talked about. If it is .csv and I click on it in the output data section of a process, then it is automatically downloaded and I have to open an additional program such as excel etc. to read it. If it is labelled as .txt then I can click on it in browser and read it without downloading, unless I specifically choose to download it. 

Right now it is more beneficial to be able to read the information in browser than saving it as .csv.

**Comment by soichih** [comment]
I've added test/csv file handler for brain-lifes's file browser. .csv should be displayed inline - with some nice syntax highlighting. 

For larger .csv files (like >1MB) brain-life will download it to user's browser instead of opening it inline. I wish there is a way to associate .csv file type with google's spreadsheet app, but I don't think they support that. There might be some browser plugin that can open .csv on browser though.

**Comment by kitchell** [comment]
awesome, thanks. Ive changed it to csv and removed the json. I am going to keep the name, so when the data is downloaded, it is clear what type of output it is.
